/*
 * generated by Xtext 2.13.0
 */
package atree.xtext.ide

import atree.xtext.BbtRuntimeModule
import atree.xtext.BbtStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BbtIdeSetup extends BbtStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BbtRuntimeModule, new BbtIdeModule))
	}
	
}
