/*
 * generated by Xtext 2.13.0
 */
package atree.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BbtStandaloneSetup extends BbtStandaloneSetupGenerated {

	def static void doSetup() {
		new BbtStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
